include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore
    always_use_package_imports: ignore
    invalid_annotation_target: ignore
    avoid_print: ignore
    unused_field: ignore
    use_build_context_synchronously: ignore
    eol_at_end_of_file: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "backups/**"

  plugins:
    - custom_lint
