name: boilerplate_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  logger: ^2.4.0
  json_annotation: ^4.9.0
  dio: ^5.4.0
  flutter_secure_storage: ^4.2.1
  connectivity_plus: ^6.1.3
  sentry_flutter: ^8.14.1
  dartz: ^0.10.1
  envied: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.3.9
  retrofit_generator: ^9.0.0
  json_serializable: ^6.9.4
  freezed: ^2.4.5
  # custom_lint: ^0.5.6
  # lint: ^2.3.0
  # riverpod_lint: ^2.1.1

flutter:

  uses-material-design: true

scripts:
  init: fvm flutter clean &&  fvm flutter pub get && fvm flutter pub run build_runner build --delete-conflicting-outputs
  build: fvm flutter pub run build_runner build --delete-conflicting-outputs
  watch: fvm flutter pub run build_runner watch
  format: fvm flutter format lib
  android: fvm flutter build appbundle
  ios: fvm flutter build ipa
  get: fvm flutter pub get
